services:
  db:
    ports:
      - "127.0.0.1:5432:5432"

  api:
    build:
      context: ../backend
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    build:
      context: ../frontend
    ports:
      - "127.0.0.1:8080:80"
