"""create schema_c tables and movies.schema_c_status

Revision ID: 55e4c873240e
Revises: e659f1b857ca
Create Date: 2026-05-23 04:13:49.228603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55e4c873240e'
down_revision: Union[str, Sequence[str], None] = 'e659f1b857ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmosphere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atmosphere_movie_id'), 'atmosphere', ['movie_id'], unique=True)
    op.create_table('character_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('char_index', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'char_index')
    )
    op.create_index(op.f('ix_character_descriptions_movie_id'), 'character_descriptions', ['movie_id'], unique=False)
    op.create_table('plot_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'kind')
    )
    op.create_index(op.f('ix_plot_variants_movie_id'), 'plot_variants', ['movie_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('quote_index', sa.Integer(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('attributed_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'quote_index')
    )
    op.create_index(op.f('ix_quotes_movie_id'), 'quotes', ['movie_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mood', sa.Text(), nullable=False),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'scene_index')
    )
    op.create_index(op.f('ix_scenes_movie_id'), 'scenes', ['movie_id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('theme_index', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'theme_index')
    )
    op.create_index(op.f('ix_themes_movie_id'), 'themes', ['movie_id'], unique=False)
    op.add_column('movies', sa.Column('schema_c_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'schema_c_status')
    op.drop_index(op.f('ix_themes_movie_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_scenes_movie_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_quotes_movie_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_plot_variants_movie_id'), table_name='plot_variants')
    op.drop_table('plot_variants')
    op.drop_index(op.f('ix_character_descriptions_movie_id'), table_name='character_descriptions')
    op.drop_table('character_descriptions')
    op.drop_index(op.f('ix_atmosphere_movie_id'), table_name='atmosphere')
    op.drop_table('atmosphere')
    # ### end Alembic commands ###
