"""add credit unique constraints

Revision ID: 5a86fe44f188
Revises: 5de4916cc3ad
Create Date: 2026-05-22 08:05:23.909099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a86fe44f188'
down_revision: Union[str, Sequence[str], None] = '5de4916cc3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_movie_cast_movie_person', 'movie_cast', ['movie_id', 'person_id'])
    op.create_unique_constraint('uq_movie_crew_movie_person_job', 'movie_crew', ['movie_id', 'person_id', 'job'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movie_crew_movie_person_job', 'movie_crew', type_='unique')
    op.drop_constraint('uq_movie_cast_movie_person', 'movie_cast', type_='unique')
    # ### end Alembic commands ###
