"""add movie enrichment columns

Revision ID: 5de4916cc3ad
Revises: 735aac05234f
Create Date: 2026-05-22 00:28:38.917971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de4916cc3ad'
down_revision: Union[str, Sequence[str], None] = '735aac05234f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('original_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'original_language')
    op.drop_column('movies', 'vote_count')
    op.drop_column('movies', 'vote_average')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'tagline')
    op.drop_column('movies', 'overview')
    # ### end Alembic commands ###
