"""create relational schema

Revision ID: 735aac05234f
Revises: 2f02bb35ec9d
Create Date: 2026-05-21 11:59:51.391039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735aac05234f'
down_revision: Union[str, Sequence[str], None] = '2f02bb35ec9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.BigInteger(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_imdb_id'), 'people', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table('movie_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=300), nullable=True),
    sa.Column('billing_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_cast_movie_id'), 'movie_cast', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_cast_person_id'), 'movie_cast', ['person_id'], unique=False)
    op.create_table('movie_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_crew_movie_id'), 'movie_crew', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_crew_person_id'), 'movie_crew', ['person_id'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('source_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'source', 'lang')
    )
    op.create_index(op.f('ix_source_texts_movie_id'), 'source_texts', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_texts_movie_id'), table_name='source_texts')
    op.drop_table('source_texts')
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_movie_crew_person_id'), table_name='movie_crew')
    op.drop_index(op.f('ix_movie_crew_movie_id'), table_name='movie_crew')
    op.drop_table('movie_crew')
    op.drop_index(op.f('ix_movie_cast_person_id'), table_name='movie_cast')
    op.drop_index(op.f('ix_movie_cast_movie_id'), table_name='movie_cast')
    op.drop_table('movie_cast')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_index(op.f('ix_people_imdb_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
